// ── Language detection by browser/location ────────────────────────────────
export const detectLang = () => {
  const stored = localStorage.getItem('lang')
  if (stored) return stored
  const nav = navigator.language || navigator.languages?.[0] || 'es'
  return nav.toLowerCase().startsWith('es') ? 'es' : 'en'
}

export const copy = {
  es: {
    badge: 'Nuevo desafío cada día',
    h1a: 'Descifra el prompt.',
    h1b: 'Domina la IA.',
    sub: 'Un juego diario donde recreas el prompt de una imagen generada por IA. Obtienes score y feedback real para mejorar cada día.',
    cta1: 'Empezar',
    cta2: 'Iniciar sesión',
    stat1: 'intentos', stat2: 'usuarios', stat3: 'imágenes',
    howTag: 'Cómo funciona',
    howTitle: 'Mira cómo funciona en tiempo real',
    howDesc: 'Esta es una demostración real del juego. Observa cómo se escribe un prompt, se envía y se compara con el original.',
    steps: [
      { n: '01', t: 'Ves la imagen', d: 'Cada día hay una imagen nueva generada por IA. Tu misión: adivinar el prompt que la creó.' },
      { n: '02', t: 'Escribes tu prompt', d: 'Describes la imagen con tus palabras. Puedes intentarlo varias veces para mejorar tu score.' },
      { n: '03', t: 'Recibes feedback', d: 'La IA compara tu prompt con el original y te da un score detallado con sugerencias reales.' },
    ],
    progressTag: 'Tu progreso',
    progressTitle: 'Sigue tu evolución día a día',
    progressDesc: 'Cada intento queda registrado. Ves tu score promedio, tu mejor marca, tu racha activa y cómo mejoras con el tiempo. No es solo un juego, es una herramienta de práctica real.',
    statsLabels: ['Score promedio', 'Racha actual', 'Mejor intento', 'Posición global'],
    chartTitle: 'Score esta semana',
    chartSub: '+39 puntos de mejora',
    chartNote: 'Datos de ejemplo — el tuyo se genera con tus intentos reales',
    communityTag: 'Comunidad',
    communityTitle: 'Ranking global, progreso real',
    communityDesc: 'Cada partida suma a tu posición en el leaderboard. La liga competitiva se reinicia cada mes y el mejor prompter obtiene una badge exclusiva en su perfil.',
    communityItems: ['Leaderboard mensual con ranking ELO', 'Perfiles públicos con historial y stats', 'Badges y medallas por logros', 'Comparación directa entre usuarios'],
    tourTag: 'Torneos y eventos',
    tourTitle: 'Torneos cada 15 días',
    tourDesc: 'Además del desafío diario, hay torneos periódicos con formato sprint. Compites contra otros en un tiempo limitado con imágenes de mayor dificultad.',
    tourItems: ['Formato sprint: 5 imágenes en 24 horas', 'Medallas exclusivas por edición', 'Premio premium para el ganador', 'Badge permanente en el perfil'],
    tourLive: 'En curso', tourEnds: 'Finaliza en 2 días', tourName: 'Prompt Sprint #2',
    tourCardDesc: '5 imágenes, dificultad alta, 24 horas para completar. El ganador se lleva una medalla exclusiva y suscripción premium.',
    tourParticipants: 'participantes',
    guidesTag: 'Guías',
    guidesTitle: 'Aprende a escribir mejores prompts',
    guidesDesc: 'No es solo jugar. Hay una sección de guías con técnicas reales de prompting: cómo describir estilos, composición, iluminación, referencias artísticas y más.',
    guidesItems: ['Técnicas de descripción visual', 'Estilos artísticos y referencias', 'Composición y encuadre', 'Prompts para distintos modelos de IA'],
    guidesLink: 'Ver guías',
    guides: [
      { t: 'Cómo describir estilos artísticos', tag: 'Básico', time: '5 min' },
      { t: 'Composición y perspectiva en prompts', tag: 'Intermedio', time: '8 min' },
      { t: 'Referencias de iluminación y color', tag: 'Avanzado', time: '10 min' },
    ],
    orgTag: 'Para organizaciones',
    orgTitle: 'Útil para empresas y colegios',
    orgDesc: 'PrompTool no es solo para uso individual. Equipos de trabajo y aulas pueden usarlo como herramienta de entrenamiento en IA generativa.',
    orgCards: [
      { icon: 'building', t: 'Equipos de trabajo', d: 'Crea una empresa, invita a tu equipo y sigue el progreso de cada miembro desde un panel centralizado.' },
      { icon: 'graduation', t: 'Aulas y colegios', d: 'Ideal para clases de tecnología o diseño. Los estudiantes aprenden prompting de forma práctica y medible.' },
      { icon: 'chart', t: 'Panel de analytics', d: 'Ves quién jugó, cuánto mejoró, scores promedio del equipo y comparativas entre miembros.' },
      { icon: 'target', t: 'Desafíos internos', d: 'Los admins pueden crear desafíos exclusivos para su organización con imágenes propias.' },
      { icon: 'link', t: 'Invitación por link', d: 'Suma miembros con un link de invitación. Sin fricción, sin configuración compleja.' },
      { icon: 'trophy', t: 'Ranking interno', d: 'Cada empresa tiene su propio ranking. Competencia sana dentro del equipo.' },
    ],
    profileTag: 'Perfiles',
    profileTitle: 'Tu perfil, tu historial',
    profileDesc: 'Cada usuario tiene un perfil público con su historial de intentos, stats, medallas ganadas y posición en el ranking. Puedes personalizar tu bio, links sociales y colores.',
    profileItems: ['Historial completo de intentos', 'Medallas y badges desbloqueadas', 'Stats: ELO, promedio, racha, mejor score', 'Links a redes sociales y portfolio', 'Perfil personalizable con color de acento'],
    profileMember: 'Miembro desde enero 2025',
    ctaTitle: '¿Listo para empezar?',
    ctaDesc: 'Tu primer desafío te espera.',
    ctaPlay: 'Jugar ahora',
    ctaSignup: 'Crear cuenta',
    community: 'Comunidad',
    noSlides: 'Las mejores jugadas de la comunidad aparecerán aquí.',
    sectionLabels: ['Inicio', 'Cómo funciona', 'Tu progreso', 'Comunidad', 'Torneos', 'Guías', 'Para equipos', 'Perfiles', 'Empezar'],
    skipToContent: 'Saltar al contenido',
    sceneDescription: 'Fondo decorativo con tarjetas de prompts de ejemplo escribiéndose y flotando suavemente.',
    scrollDown: 'Bajar',
    forCompanies: 'Para empresas y equipos',
    forTeamsCta: 'Para equipos y empresas',
  },
  en: {
    badge: 'New challenge every day',
    h1a: 'Decode the prompt.',
    h1b: 'Master AI.',
    sub: 'A daily game where you recreate the prompt of an AI-generated image. Get a real score and feedback to improve every day.',
    cta1: 'Get started',
    cta2: 'Sign in',
    stat1: 'attempts', stat2: 'users', stat3: 'images',
    howTag: 'How it works',
    howTitle: 'See how it works in real time',
    howDesc: 'This is a real demonstration of the game. Watch how a prompt is written, submitted, and compared to the original.',
    steps: [
      { n: '01', t: 'See the image', d: 'Every day there is a new AI-generated image. Your mission: guess the prompt that created it.' },
      { n: '02', t: 'Write your prompt', d: 'Describe the image in your own words. You can try multiple times to improve your score.' },
      { n: '03', t: 'Get feedback', d: 'The AI compares your prompt to the original and gives you a detailed score with real suggestions.' },
    ],
    progressTag: 'Your progress',
    progressTitle: 'Track your evolution day by day',
    progressDesc: 'Every attempt is recorded. See your average score, best mark, active streak and how you improve over time. Not just a game — a real practice tool.',
    statsLabels: ['Avg score', 'Current streak', 'Best attempt', 'Global rank'],
    chartTitle: 'Score this week',
    chartSub: '+39 point improvement',
    chartNote: 'Sample data — yours is generated from your real attempts',
    communityTag: 'Community',
    communityTitle: 'Global ranking, real progress',
    communityDesc: 'Every game counts toward your leaderboard position. The competitive league resets monthly and the top prompter earns an exclusive badge on their profile.',
    communityItems: ['Monthly leaderboard with ELO ranking', 'Public profiles with history and stats', 'Badges and medals for achievements', 'Head-to-head comparison between users'],
    tourTag: 'Tournaments & events',
    tourTitle: 'Tournaments every 15 days',
    tourDesc: 'Beyond the daily challenge, there are periodic sprint-format tournaments. Compete against others in a time-limited format with harder images.',
    tourItems: ['Sprint format: 5 images in 24 hours', 'Exclusive medals per edition', 'Premium prize for the winner', 'Permanent badge on profile'],
    tourLive: 'Live', tourEnds: 'Ends in 2 days', tourName: 'Prompt Sprint #2',
    tourCardDesc: '5 images, hard difficulty, 24 hours to complete. The winner gets an exclusive medal and a premium subscription.',
    tourParticipants: 'participants',
    guidesTag: 'Guides',
    guidesTitle: 'Learn to write better prompts',
    guidesDesc: 'Not just a game. There is a guides section with real prompting techniques: how to describe styles, composition, lighting, artistic references and more.',
    guidesItems: ['Visual description techniques', 'Artistic styles and references', 'Composition and framing', 'Prompts for different AI models'],
    guidesLink: 'View guides',
    guides: [
      { t: 'How to describe artistic styles', tag: 'Basic', time: '5 min' },
      { t: 'Composition and perspective in prompts', tag: 'Intermediate', time: '8 min' },
      { t: 'Lighting and color references', tag: 'Advanced', time: '10 min' },
    ],
    orgTag: 'For organizations',
    orgTitle: 'Built for teams and schools',
    orgDesc: 'PrompTool is not just for individual use. Work teams and classrooms can use it as a generative AI training tool.',
    orgCards: [
      { icon: 'building', t: 'Work teams', d: 'Create a company, invite your team and track each member\'s progress from a centralized dashboard.' },
      { icon: 'graduation', t: 'Classrooms & schools', d: 'Great for technology or design classes. Students learn prompting in a practical, measurable way.' },
      { icon: 'chart', t: 'Analytics dashboard', d: 'See who played, how much they improved, team average scores and member comparisons.' },
      { icon: 'target', t: 'Internal challenges', d: 'Admins can create exclusive challenges for their organization with custom images.' },
      { icon: 'link', t: 'Invite by link', d: 'Add members with an invite link. No friction, no complex setup.' },
      { icon: 'trophy', t: 'Internal ranking', d: 'Each company has its own ranking. Healthy competition within the team.' },
    ],
    profileTag: 'Profiles',
    profileTitle: 'Your profile, your history',
    profileDesc: 'Every user has a public profile with their attempt history, stats, earned medals and ranking position. Customize your bio, social links and accent color.',
    profileItems: ['Full attempt history', 'Unlocked medals and badges', 'Stats: ELO, average, streak, best score', 'Social and portfolio links', 'Customizable profile with accent color'],
    profileMember: 'Member since January 2025',
    ctaTitle: 'Ready to start?',
    ctaDesc: 'Your first challenge is waiting.',
    ctaPlay: 'Play now',
    ctaSignup: 'Create account',
    community: 'Community',
    noSlides: 'The best community plays will appear here.',
    sectionLabels: ['Start', 'How it works', 'Your progress', 'Community', 'Tournaments', 'Guides', 'For teams', 'Profiles', 'Get started'],
    skipToContent: 'Skip to content',
    sceneDescription: 'Decorative background with sample prompt cards typing themselves and gently floating.',
    scrollDown: 'Scroll down',
    forCompanies: 'For companies & teams',
    forTeamsCta: 'For teams & companies',
  },
}
